# Generated by Django 5.2.6 on 2025-12-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_remove_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='whatsapp_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
