# Generated by Django 5.2.6 on 2025-10-10 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cedula',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe contener entre 8 y 12 dígitos numéricos.', regex='^\\d{8,12}$')], verbose_name='Número de Cédula'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de contratación'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin', 'Administrador'), ('employee', 'Empleado')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
