# Generated by Django 5.2.7 on 2025-11-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tenant_privatenote_userprofile_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin', 'Administrador'), ('employer', 'Empleador'), ('employee', 'Empleado')], default='employee', max_length=20),
        ),
    ]
