# Generated by Django 5.2.6 on 2025-11-25 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tenant_configuration'),
        ('users', '0005_alter_userprofile_role'),
    ]

    operations = [
    ]
