# Generated by Django 5.2.6 on 2025-12-26 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('sales', '0006_saleitem_setnull_color_variant'),
        ('users', '0010_subscriptionplan_enable_daily_backups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DianClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('13', 'Cédula de ciudadanía'), ('31', 'NIT'), ('11', 'Registro civil'), ('12', 'Tarjeta de identidad'), ('21', 'Tarjeta de extranjería'), ('22', 'Cédula de extranjería'), ('41', 'Pasaporte'), ('42', 'Documento de identificación extranjero')], default='13', max_length=2)),
                ('person_type', models.CharField(choices=[('1', 'Persona Jurídica'), ('2', 'Persona Natural')], default='2', max_length=1)),
                ('tax_regimen', models.CharField(default='49', help_text='48: IVA, 49: No IVA', max_length=10)),
                ('fiscal_responsibilities', models.CharField(default='R-99-PN', max_length=100)),
                ('commercial_name', models.CharField(blank=True, max_length=200)),
                ('city_code', models.CharField(help_text='Código DANE municipio', max_length=10)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dian_info', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='DianCompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('1', 'Producción'), ('2', 'Pruebas')], default='2', max_length=1)),
                ('software_id', models.CharField(blank=True, help_text='ID del software proporcionado por la DIAN', max_length=100)),
                ('software_pin', models.CharField(blank=True, help_text='PIN del software', max_length=100)),
                ('test_set_id', models.CharField(blank=True, help_text='Test Set ID para habilitación', max_length=100)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='dian/certs/')),
                ('certificate_password', models.CharField(blank=True, max_length=100)),
                ('nit', models.CharField(blank=True, max_length=20)),
                ('dv', models.CharField(blank=True, help_text='Dígito de verificación', max_length=1)),
                ('tax_regimen', models.CharField(default='48', help_text='48: Impuesto sobre las ventas - IVA, 49: No responsable de IVA', max_length=10)),
                ('fiscal_responsibilities', models.CharField(default='R-99-PN', help_text='Códigos separados por ;', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dian_config', to='users.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DianResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_number', models.CharField(max_length=50)),
                ('prefix', models.CharField(blank=True, max_length=10)),
                ('from_number', models.BigIntegerField()),
                ('to_number', models.BigIntegerField()),
                ('current_number', models.BigIntegerField(default=0)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('technical_key', models.CharField(help_text='Clave técnica de la resolución', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dian_resolutions', to='users.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cufe', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('qrcode_data', models.TextField(blank=True, null=True)),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='dian/xmls/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='dian/pdfs/')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('signed', 'Firmada'), ('sent', 'Enviada DIAN'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('error', 'Error Técnico')], default='draft', max_length=20)),
                ('dian_response', models.JSONField(blank=True, default=dict)),
                ('dian_errors', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='einvoicing.dianresolution')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electronic_invoice', to='sales.sale')),
            ],
        ),
    ]
