# Generated by Django 5.2.7 on 2025-11-12 19:28

import django.db.models.deletion
from django.db import migrations, models


def migrate_category_to_fk(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Category = apps.get_model('products', 'Category')
    for p in Product.objects.all():
        p.category_fk_id = None
        # Optional mapping by name if exists
        try:
            if isinstance(p.category, str):
                cat = Category.objects.filter(name=p.category).first()
                if cat:
                    p.category_fk_id = cat.id
        except Exception:
            pass
        p.save(update_fields=['category_fk'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_sku_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.RunPython(migrate_category_to_fk, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_fk',
            new_name='category',
        ),
    ]
