# Generated by Django 5.2.6 on 2025-12-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productfeature_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=19.0, help_text='Porcentaje de IVA (0, 5, 19)', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_measure',
            field=models.CharField(default='94', help_text='Código de unidad (94=Unidad, KGM=Kilogramo)', max_length=10),
        ),
    ]
