// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gixcwvbohflkdvtpurpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpeGN3dmJvaGZsa2R2dHB1cnBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwODA4NzIsImV4cCI6MjA2NjY1Njg3Mn0.bh5x9UaUbp_V9YOLBEqWzeOeUAsrCIf5k3IWXlll52A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);