# Generated by Django 5.2.6 on 2026-01-06 18:38

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='entry_date',
            field=models.DateField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
