# Generated by Django 5.2.6 on 2026-01-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_entry_date_service_exit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='third_party_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
