# Generated by Django 5.2.7 on 2025-11-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0002_visibleproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='websettings',
            name='site_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
