# Generated by Django 5.2.7 on 2025-11-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0004_accesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websettings',
            name='site_url',
            field=models.URLField(blank=True, default='http://192.168.1.56:8080/'),
        ),
    ]
