# Generated by Django 5.2.7 on 2025-11-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0007_websettings_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websettings',
            name='site_url',
            field=models.URLField(blank=True, default='http://localhost:8080/'),
        ),
    ]
