# Generated by Django 5.2.7 on 2025-11-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0009_paymentmethod_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='websettings',
            name='company_address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='websettings',
            name='company_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='websettings',
            name='company_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='websettings',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='websettings',
            name='company_nit',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='websettings',
            name='company_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='websettings',
            name='company_whatsapp',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
