# Generated by Django 5.2.6 on 2025-12-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0014_alter_userurl_url_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userurl',
            name='url',
            field=models.URLField(max_length=256, unique=True),
        ),
    ]
