# Generated by Django 5.2.6 on 2025-12-20 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0019_websettings_logo_size_px'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebSettings',
        ),
    ]
