# Generated by Django 5.2.6 on 2026-01-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0020_delete_websettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('github_url', models.URLField(max_length=255)),
                ('demo_url', models.URLField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, default='from-gray-500 to-gray-600', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
