# Generated by Django 5.2.6 on 2026-01-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0021_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='web/templates/'),
        ),
        migrations.AddField(
            model_name='template',
            name='page_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
