# Generated by Django 5.2.6 on 2026-01-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0022_template_image_template_page_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='template',
            name='page_types',
        ),
        migrations.AddField(
            model_name='template',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='templates/files/'),
        ),
        migrations.AlterField(
            model_name='template',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='template',
            name='demo_url',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/images/'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
