# Generated by Django 5.2.6 on 2026-01-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0023_remove_template_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
