# Generated by Django 5.2.6 on 2026-01-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0025_template_is_personal_template_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='page_content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
