# Generated by Django 5.2.7 on 2025-11-13 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_role'),
        ('webconfig', '0006_visiblecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='websettings',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tenant'),
        ),
    ]
