# Generated by Django 5.2.6 on 2025-12-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0011_policy_privacy_userurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userurl',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
