# Generated by Django 5.2.6 on 2025-12-12 23:38

import webconfig.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0015_alter_userurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=webconfig.models.web_logo_upload_path),
        ),
    ]
