# Generated by Django 5.2.6 on 2025-12-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0017_printer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='web/banners/'),
        ),
    ]
