# Generated by Django 5.2.6 on 2025-12-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0018_alter_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='websettings',
            name='logo_size_px',
            field=models.PositiveIntegerField(default=36),
        ),
    ]
