# Generated by Django 5.2.6 on 2026-01-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_appsettings_whatsapp_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='page_content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
