# Generated by Django 5.2.7 on 2025-11-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order_number',
            field=models.CharField(default=1, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
