# Generated by Django 5.2.7 on 2025-11-12 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('cedula', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['cedula'], name='clients_cli_cedula_5b982e_idx'), models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx'), models.Index(fields=['created_at'], name='clients_cli_created_4ff9ec_idx')],
            },
        ),
    ]
