# Generated by Django 5.2.6 on 2025-12-20 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20251125_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('basic', 'Plan Básico'), ('medium', 'Plan Medio'), ('advanced', 'Plan Avanzado')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_users', models.IntegerField(default=1, help_text='Number of users allowed. -1 for unlimited.')),
                ('max_transactions_per_month', models.IntegerField(default=100, help_text='Number of transactions allowed per month. -1 for unlimited.')),
                ('enable_basic_dashboard', models.BooleanField(default=True)),
                ('enable_basic_sales', models.BooleanField(default=True)),
                ('enable_basic_stats', models.BooleanField(default=True)),
                ('enable_advanced_sales_analysis', models.BooleanField(default=False)),
                ('enable_inventory_management', models.BooleanField(default=False)),
                ('enable_detailed_reports', models.BooleanField(default=False)),
                ('enable_third_party_integrations', models.BooleanField(default=False)),
                ('enable_web_store', models.BooleanField(default=False)),
                ('enable_custom_domain', models.BooleanField(default=False)),
                ('enable_marketing_tools', models.BooleanField(default=False)),
                ('enable_api_access', models.BooleanField(default=False)),
                ('enable_priority_support', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='users.subscriptionplan'),
        ),
    ]
