# Generated by Django 5.2.6 on 2025-12-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_subscriptionplan_tenant_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='enable_user_management',
            field=models.BooleanField(default=True),
        ),
    ]
