# Generated by Django 5.2.6 on 2025-12-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_subscriptionplan_enable_user_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_categories',
            field=models.IntegerField(default=10, help_text='Number of categories allowed. -1 for unlimited.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_products',
            field=models.IntegerField(default=50, help_text='Number of products allowed. -1 for unlimited.'),
        ),
    ]
