# Generated by Django 5.2.6 on 2025-12-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_subscriptionplan_max_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='enable_daily_backups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='enable_electronic_invoicing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='enable_supplier_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='enable_whatsapp_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
