# Generated by Django 5.2.6 on 2025-12-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_subscriptionplan_enable_daily_backups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='name',
            field=models.CharField(default='Mi Negocio', max_length=255),
        ),
    ]
