# Generated by Django 5.2.6 on 2025-11-29 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productvariant'),
        ('sales', '0003_sale_status_sale_updated_at_ordernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productvariant'),
        ),
    ]
