# Generated by Django 5.2.7 on 2025-11-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_category_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_kg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width_cm',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50, unique=True, null=True, blank=True),
        ),
    ]
