# Generated by Django 5.2.7 on 2025-11-12 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_sku_productcolor_productcolorimage'),
        ('products', '0006_fill_sku_enforce_not_null'),
    ]

    operations = [
    ]
