# Generated by Django 5.2.7 on 2025-11-13 20:11

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_add_stock_to_productcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorimage',
            name='image',
            field=models.ImageField(upload_to=products.models.color_image_upload_path),
        ),
    ]
